In [1]:
range(5)

range(0, 5)

In [2]:
r = range(5)

In [5]:
for i in r:
    print(i)

0
1
2
3
4


In [1]:
list(range(5))

[0, 1, 2, 3, 4]

In [2]:
range(1, 10)

range(1, 10)

In [3]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(1, 10, 3))

[1, 4, 7]

In [6]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [7]:
import numpy as np


In [8]:
np.random.rand(5)

array([0.48630306, 0.9514831 , 0.88796822, 0.66680424, 0.78666737])

In [9]:
np.random.rand(2, 4)

array([[0.21442271, 0.73904748, 0.17484861, 0.30709742],
       [0.81809996, 0.49523107, 0.47294421, 0.41213668]])

In [10]:
np.random.randint(2, 4)

3

In [11]:
np.random.randint(2, 20)

7

In [12]:
np.random.randint(0, 1)

0

In [13]:
np.random.randint(10, 20, 5)

array([11, 13, 16, 12, 16], dtype=int32)

In [14]:
np.random.randint(1, 6, 4)

array([5, 3, 4, 2], dtype=int32)

In [15]:
np.random.rand(3)

array([0.42055175, 0.67079764, 0.43336954])

In [17]:
np.random.randint(1)

0

In [18]:
# for higher to lower does not work 
# eg., np.random.randint(30, 20, 10)

In [19]:
np.random.randint(-30, 20, 10)

array([-18,  -5, -20, -23, -19,   5, -20, -25,   6,   3], dtype=int32)

In [20]:
np.random.randint(20, 30, 10)

array([29, 20, 28, 23, 23, 27, 20, 29, 22, 21], dtype=int32)

In [21]:
np.random.randint(5, 9)   # GER THE VALUE <=1 & >=5

5

In [22]:
np.random.randint(10, 21, 3)

array([14, 14, 15], dtype=int32)

In [23]:
np.random.randint(1, 12, 10)

array([11, 10,  4,  8,  8,  1, 11,  4,  9,  6], dtype=int32)

In [25]:
np.random.randint(10, 40, (10, 10))

array([[37, 12, 16, 24, 23, 27, 10, 33, 32, 29],
       [20, 32, 13, 16, 31, 16, 35, 26, 37, 21],
       [36, 31, 23, 21, 33, 24, 36, 37, 10, 16],
       [17, 17, 34, 38, 13, 39, 23, 17, 18, 29],
       [28, 25, 11, 32, 19, 37, 26, 27, 19, 37],
       [19, 13, 23, 39, 25, 21, 20, 38, 24, 33],
       [25, 10, 27, 27, 38, 14, 39, 23, 14, 15],
       [27, 23, 35, 27, 39, 29, 16, 20, 18, 36],
       [15, 17, 33, 39, 13, 30, 19, 22, 33, 20],
       [38, 13, 33, 25, 14, 19, 33, 14, 15, 25]], dtype=int32)

In [26]:
np.random.randint(1, 100, (12, 12))


array([[85, 19, 95, 49, 30, 68, 81, 92, 36, 46, 49, 10],
       [50, 20, 40, 67, 58, 22, 55, 71, 41, 92, 76, 98],
       [53, 67, 47, 15, 92,  9, 46, 32, 18,  8, 84, 70],
       [75, 47, 36, 52,  3,  1, 15, 85, 28, 74, 28, 49],
       [21, 10, 11, 80, 51, 86, 75, 16,  8, 15, 39, 13],
       [86, 53, 22, 92, 93, 53, 22, 55, 29, 41, 65, 46],
       [72, 72, 30, 38, 87,  1, 75,  2, 14, 89, 81, 32],
       [33,  4,  9,  2, 33, 68, 45, 65,  3, 36, 27, 96],
       [67, 39, 90, 78, 63,  8, 64, 98, 47, 74, 13, 28],
       [54, 10, 42, 72, 64, 25, 29, 45, 97, 36, 88, 19],
       [29,  6, 31, 48, 70, 57,  9, 25, 37, 62, 84, 80],
       [97, 89, 41, 66, 63, 29,  9,  4, 78, 42, 54, 61]], dtype=int32)

In [27]:
np.arange(1, 13).reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
np.arange(1, 13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [30]:
b = np.random.randint(10, 20, (5, 4))
b

array([[10, 13, 12, 13],
       [16, 10, 15, 14],
       [12, 15, 15, 11],
       [14, 17, 12, 12],
       [16, 14, 15, 15]], dtype=int32)

In [31]:
type(b)

numpy.ndarray

In [32]:
b[:]

array([[10, 13, 12, 13],
       [16, 10, 15, 14],
       [12, 15, 15, 11],
       [14, 17, 12, 12],
       [16, 14, 15, 15]], dtype=int32)

In [33]:
b[1:3]

array([[16, 10, 15, 14],
       [12, 15, 15, 11]], dtype=int32)

In [34]:
b

array([[10, 13, 12, 13],
       [16, 10, 15, 14],
       [12, 15, 15, 11],
       [14, 17, 12, 12],
       [16, 14, 15, 15]], dtype=int32)

In [35]:
b[1, 2]

np.int32(15)

In [36]:
b[1, 3]

np.int32(14)

In [37]:
b[1, -1]

np.int32(14)

In [38]:
b

array([[10, 13, 12, 13],
       [16, 10, 15, 14],
       [12, 15, 15, 11],
       [14, 17, 12, 12],
       [16, 14, 15, 15]], dtype=int32)

In [39]:
b[2:3]

array([[12, 15, 15, 11]], dtype=int32)

In [40]:
b

array([[10, 13, 12, 13],
       [16, 10, 15, 14],
       [12, 15, 15, 11],
       [14, 17, 12, 12],
       [16, 14, 15, 15]], dtype=int32)

In [41]:
b[0:-2]

array([[10, 13, 12, 13],
       [16, 10, 15, 14],
       [12, 15, 15, 11]], dtype=int32)

In [42]:
b

array([[10, 13, 12, 13],
       [16, 10, 15, 14],
       [12, 15, 15, 11],
       [14, 17, 12, 12],
       [16, 14, 15, 15]], dtype=int32)

In [43]:
b[0, 2]

np.int32(12)

In [44]:
b

array([[10, 13, 12, 13],
       [16, 10, 15, 14],
       [12, 15, 15, 11],
       [14, 17, 12, 12],
       [16, 14, 15, 15]], dtype=int32)

In [45]:
b[-5, -3]

np.int32(13)

In [46]:
b[-4, 3]

np.int32(14)

In [47]:
np.random.randint(10, 20, (4, 4))

array([[14, 13, 18, 15],
       [18, 10, 12, 18],
       [15, 18, 14, 19],
       [11, 10, 10, 13]], dtype=int32)

In [48]:
b

array([[10, 13, 12, 13],
       [16, 10, 15, 14],
       [12, 15, 15, 11],
       [14, 17, 12, 12],
       [16, 14, 15, 15]], dtype=int32)

In [49]:
b[-4, -2]

np.int32(15)

In [50]:
b

array([[10, 13, 12, 13],
       [16, 10, 15, 14],
       [12, 15, 15, 11],
       [14, 17, 12, 12],
       [16, 14, 15, 15]], dtype=int32)

In [51]:
b[-4, 2]

np.int32(15)

In [52]:
b[:]

array([[10, 13, 12, 13],
       [16, 10, 15, 14],
       [12, 15, 15, 11],
       [14, 17, 12, 12],
       [16, 14, 15, 15]], dtype=int32)

# Operation

In [54]:
a = np.random.randint(10, 20, 10)
a

array([14, 17, 14, 15, 11, 18, 10, 14, 10, 16], dtype=int32)

In [55]:
id(a)

2589502581200

In [57]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [59]:
arr2 = np.random.randint(0, 100, (10, 10))
arr2

array([[63, 83, 95, 60, 20, 15, 50, 74,  2, 83],
       [54, 74, 18, 86, 93, 41, 78, 84, 68, 12],
       [16, 46, 77, 11, 21, 93, 65, 18,  1, 50],
       [ 9,  9, 62, 44, 32, 62, 91,  3, 76, 75],
       [22, 41, 85, 57, 87, 44, 78, 91, 95,  8],
       [67, 52, 36, 62, 40, 36, 45, 89, 29, 15],
       [ 4, 95, 24, 34, 88, 30, 66, 10, 69, 93],
       [63, 47, 90, 67, 96,  4, 25, 51, 30, 96],
       [18, 67, 15, 99,  2, 61, 24, 13, 23, 40],
       [74, 55, 20, 71, 72, 29, 91, 59, 69, 21]], dtype=int32)

In [60]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [61]:
arr

array([0, 1, 2, 3, 4, 5])

In [62]:
arr[:4]

array([0, 1, 2, 3])

In [63]:
arr2[:]

array([[63, 83, 95, 60, 20, 15, 50, 74,  2, 83],
       [54, 74, 18, 86, 93, 41, 78, 84, 68, 12],
       [16, 46, 77, 11, 21, 93, 65, 18,  1, 50],
       [ 9,  9, 62, 44, 32, 62, 91,  3, 76, 75],
       [22, 41, 85, 57, 87, 44, 78, 91, 95,  8],
       [67, 52, 36, 62, 40, 36, 45, 89, 29, 15],
       [ 4, 95, 24, 34, 88, 30, 66, 10, 69, 93],
       [63, 47, 90, 67, 96,  4, 25, 51, 30, 96],
       [18, 67, 15, 99,  2, 61, 24, 13, 23, 40],
       [74, 55, 20, 71, 72, 29, 91, 59, 69, 21]], dtype=int32)

In [64]:
arr2[0:5]

array([[63, 83, 95, 60, 20, 15, 50, 74,  2, 83],
       [54, 74, 18, 86, 93, 41, 78, 84, 68, 12],
       [16, 46, 77, 11, 21, 93, 65, 18,  1, 50],
       [ 9,  9, 62, 44, 32, 62, 91,  3, 76, 75],
       [22, 41, 85, 57, 87, 44, 78, 91, 95,  8]], dtype=int32)

In [65]:
arr2


array([[63, 83, 95, 60, 20, 15, 50, 74,  2, 83],
       [54, 74, 18, 86, 93, 41, 78, 84, 68, 12],
       [16, 46, 77, 11, 21, 93, 65, 18,  1, 50],
       [ 9,  9, 62, 44, 32, 62, 91,  3, 76, 75],
       [22, 41, 85, 57, 87, 44, 78, 91, 95,  8],
       [67, 52, 36, 62, 40, 36, 45, 89, 29, 15],
       [ 4, 95, 24, 34, 88, 30, 66, 10, 69, 93],
       [63, 47, 90, 67, 96,  4, 25, 51, 30, 96],
       [18, 67, 15, 99,  2, 61, 24, 13, 23, 40],
       [74, 55, 20, 71, 72, 29, 91, 59, 69, 21]], dtype=int32)

In [66]:
arr2[1, 4]

np.int32(93)

In [67]:
arr2


array([[63, 83, 95, 60, 20, 15, 50, 74,  2, 83],
       [54, 74, 18, 86, 93, 41, 78, 84, 68, 12],
       [16, 46, 77, 11, 21, 93, 65, 18,  1, 50],
       [ 9,  9, 62, 44, 32, 62, 91,  3, 76, 75],
       [22, 41, 85, 57, 87, 44, 78, 91, 95,  8],
       [67, 52, 36, 62, 40, 36, 45, 89, 29, 15],
       [ 4, 95, 24, 34, 88, 30, 66, 10, 69, 93],
       [63, 47, 90, 67, 96,  4, 25, 51, 30, 96],
       [18, 67, 15, 99,  2, 61, 24, 13, 23, 40],
       [74, 55, 20, 71, 72, 29, 91, 59, 69, 21]], dtype=int32)

In [68]:
arr2[-5, 5]

np.int32(36)

In [69]:
arr2[-5, -5]

np.int32(36)

In [70]:
arr2[-1, -2]

np.int32(69)

In [71]:
arr2

array([[63, 83, 95, 60, 20, 15, 50, 74,  2, 83],
       [54, 74, 18, 86, 93, 41, 78, 84, 68, 12],
       [16, 46, 77, 11, 21, 93, 65, 18,  1, 50],
       [ 9,  9, 62, 44, 32, 62, 91,  3, 76, 75],
       [22, 41, 85, 57, 87, 44, 78, 91, 95,  8],
       [67, 52, 36, 62, 40, 36, 45, 89, 29, 15],
       [ 4, 95, 24, 34, 88, 30, 66, 10, 69, 93],
       [63, 47, 90, 67, 96,  4, 25, 51, 30, 96],
       [18, 67, 15, 99,  2, 61, 24, 13, 23, 40],
       [74, 55, 20, 71, 72, 29, 91, 59, 69, 21]], dtype=int32)

In [72]:
arr2[::-1]

array([[74, 55, 20, 71, 72, 29, 91, 59, 69, 21],
       [18, 67, 15, 99,  2, 61, 24, 13, 23, 40],
       [63, 47, 90, 67, 96,  4, 25, 51, 30, 96],
       [ 4, 95, 24, 34, 88, 30, 66, 10, 69, 93],
       [67, 52, 36, 62, 40, 36, 45, 89, 29, 15],
       [22, 41, 85, 57, 87, 44, 78, 91, 95,  8],
       [ 9,  9, 62, 44, 32, 62, 91,  3, 76, 75],
       [16, 46, 77, 11, 21, 93, 65, 18,  1, 50],
       [54, 74, 18, 86, 93, 41, 78, 84, 68, 12],
       [63, 83, 95, 60, 20, 15, 50, 74,  2, 83]], dtype=int32)

In [73]:
arr2


array([[63, 83, 95, 60, 20, 15, 50, 74,  2, 83],
       [54, 74, 18, 86, 93, 41, 78, 84, 68, 12],
       [16, 46, 77, 11, 21, 93, 65, 18,  1, 50],
       [ 9,  9, 62, 44, 32, 62, 91,  3, 76, 75],
       [22, 41, 85, 57, 87, 44, 78, 91, 95,  8],
       [67, 52, 36, 62, 40, 36, 45, 89, 29, 15],
       [ 4, 95, 24, 34, 88, 30, 66, 10, 69, 93],
       [63, 47, 90, 67, 96,  4, 25, 51, 30, 96],
       [18, 67, 15, 99,  2, 61, 24, 13, 23, 40],
       [74, 55, 20, 71, 72, 29, 91, 59, 69, 21]], dtype=int32)

In [74]:
arr2[::-2]

array([[74, 55, 20, 71, 72, 29, 91, 59, 69, 21],
       [63, 47, 90, 67, 96,  4, 25, 51, 30, 96],
       [67, 52, 36, 62, 40, 36, 45, 89, 29, 15],
       [ 9,  9, 62, 44, 32, 62, 91,  3, 76, 75],
       [54, 74, 18, 86, 93, 41, 78, 84, 68, 12]], dtype=int32)

In [76]:
arr2[::-3]

array([[74, 55, 20, 71, 72, 29, 91, 59, 69, 21],
       [ 4, 95, 24, 34, 88, 30, 66, 10, 69, 93],
       [ 9,  9, 62, 44, 32, 62, 91,  3, 76, 75],
       [63, 83, 95, 60, 20, 15, 50, 74,  2, 83]], dtype=int32)

In [77]:
arr2[:-3]

array([[63, 83, 95, 60, 20, 15, 50, 74,  2, 83],
       [54, 74, 18, 86, 93, 41, 78, 84, 68, 12],
       [16, 46, 77, 11, 21, 93, 65, 18,  1, 50],
       [ 9,  9, 62, 44, 32, 62, 91,  3, 76, 75],
       [22, 41, 85, 57, 87, 44, 78, 91, 95,  8],
       [67, 52, 36, 62, 40, 36, 45, 89, 29, 15],
       [ 4, 95, 24, 34, 88, 30, 66, 10, 69, 93]], dtype=int32)

In [79]:
arr

array([0, 1, 2, 3, 4, 5])

In [80]:
arr.max()

np.int64(5)

In [81]:
arr.min()

np.int64(0)

In [82]:
arr

array([0, 1, 2, 3, 4, 5])

In [83]:
arr.mean()

np.float64(2.5)

In [84]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [85]:
from numpy import *
a = array([1, 2, 3, 4, 9])
median(a)

np.float64(3.0)

## Without work on import* can you please find the median, mode

In [86]:
arr

array([0, 1, 2, 3, 4, 5])

In [88]:
arr.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [89]:
arr.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [90]:
arr.reshape(1, 6)

array([[0, 1, 2, 3, 4, 5]])

In [91]:
arr.reshape(2, 4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [92]:
arr

array([0, 1, 2, 3, 4, 5])

In [93]:
arr.rehspae(2, 3, order='C')

AttributeError: 'numpy.ndarray' object has no attribute 'rehspae'

In [94]:
arr.rehspae(2, 3, order='c')

AttributeError: 'numpy.ndarray' object has no attribute 'rehspae'

In [95]:
arr.reshape(2, 3, order='F')
# Print element with fortran

array([[0, 2, 4],
       [1, 3, 5]])

In [96]:
arr.reshape(2, 3, order='A')
# A almost give you c type output

array([[0, 1, 2],
       [3, 4, 5]])

In [97]:
arr


array([0, 1, 2, 3, 4, 5])

In [98]:
arr.reshape(2, 3
           
           )

array([[0, 1, 2],
       [3, 4, 5]])

In [99]:
arr.reshape(1, 4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [100]:
arr.reshape(3, 3
           )

ValueError: cannot reshape array of size 6 into shape (3,3)

In [101]:
arr.reshape(3, 2
           )

array([[0, 1],
       [2, 3],
       [4, 5]])

## Inde