## 1. Importing Numpy

In [2]:
import numpy as np

## 2. Creating Arrays

#### From a list

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)   # Creating a 1D array

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)   # Creating a 2D array

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


#### Special arrays

In [5]:
zeros_arr = np.zeros(5)   # Array of 5 zeros
print(zeros_arr)

ones_arr = np.ones((2, 3))   # 2x3 array of ones
print(ones_arr)

empty_arr = np.empty(3)   # Unintialized array (content is random)
print(empty_arr)

identity_arr = np.eye(3)   # 3x3 identity matrix
print(identity_arr)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0.0000000e+000 0.0000000e+000 4.9832622e+151]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Range of values

In [10]:
range_arr = np.arange(0, 10, 2)   # [0, 2, 4, 6, 8] (similar to range())
print(range_arr)

linspace_arr = np.linspace(0, 1, 5)   # 5 numbers evenly spaced between 0 and 1
print(linspace_arr)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# linspace_arr1 = np.linspace(0, 10, 3)
# print(linspace_arr1)

#### Random arrays

In [18]:
rand_arr = np.random.rand(3,3)   # 3x3 array with random values between 0 and 1
print(rand_arr)
randn_arr = np.random.randn(3,3)   # Normally distributed random numbers
print(randn_arr)
randint_arr = np.random.randint(0, 10, size=(2, 3))   # 2x3 array of random integers
print(randint_arr)

[[0.30080286 0.49333309 0.86965731]
 [0.88939316 0.41975612 0.91405953]
 [0.38163171 0.8068163  0.38530441]]
[[-0.51383759  0.82749103 -2.21426955]
 [-0.0218357  -1.01971654 -0.81367381]
 [ 0.60204122  0.24957629  0.23808189]]
[[4 3 5]
 [7 2 2]]


## 3. Array Operations

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#### Element-wise addition

In [21]:
print(a+b)

[5 7 9]


#### Element-wise substraction

In [22]:
print(a-b)

[-3 -3 -3]


#### Element-wise multiplication

In [23]:
print(a*b)

[ 4 10 18]


#### Element-wise division

In [24]:
print(a/b)

[0.25 0.4  0.5 ]


#### Element-wise exponentiation

In [25]:
print(a**2)

[1 4 9]


### Element-wise operations

In [26]:
print(np.square(a))
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))

[1 4 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]


### Dot product

In [29]:
dot_product = np.dot(a, b)
print(dot_product)
# 1*4 + 2*5 + 3*6

# Or using @ operatot (Python 3.5+)
dot_product = a @ b
print(dot_product)

32
32


## 4. Array Manipulation

#### Reshaping

In [31]:
arr = np.arange(9)
print(arr)
reshaped = arr.reshape(3, 3)   # Converts 3x3 array
print(reshaped)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Transpose

In [32]:
transposed = reshaped.T   # Swap rows and columns
print(transposed)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


#### Flattening

In [33]:
flattened = reshaped.flatten()   # Returned 1D array
print(flattened)

[0 1 2 3 4 5 6 7 8]


#### Concatenation

In [37]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [38]:
# Vertical stack (row-wise)
vstacked = np.vstack((a, b))
print(vstacked)

[[1 2]
 [3 4]
 [5 6]]


In [39]:
# Horizontal stack (column-wise)
hstacked = np.hstack((a, b.T))
print(hstacked)

[[1 2 5]
 [3 4 6]]


In [43]:
# General Concatenation
concat = np.concatenate((a, b), axis=0)   # Same as vstack
print(concat)

[[1 2]
 [3 4]
 [5 6]]


#### Splitting

In [46]:
arr = np.arange(9).reshape(3,3)
print(arr)
sub_arrays =  np.split(arr,3)   # Split into 3 equal parts along axis 0
print(sub_arrays)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


## 5. Indexing and Slicing

#### Basic indexing 


In [47]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[-1])

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[0, 1])

1
5
2


#### Slicing

In [51]:
print(arr)
print(arr[1:4])
print(arr[:3])
print(arr[::2])

print(matrix)
print(matrix[:, 1])   # (all rows, column1)
print(matrix[1, :])   # (row 1, all columns)

[1 2 3 4 5]
[2 3 4]
[1 2 3]
[1 3 5]
[[1 2 3]
 [4 5 6]]
[2 5]
[4 5 6]


#### Boolean indexing

In [52]:
print([arr[arr>3]])

[array([4, 5])]


## 6. Statistical Operations

#### Basic Statistics

In [53]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))   # (standard deviation)
print(np.var(arr))   # (variance)

print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))

3.0
3.0
1.4142135623730951
2.0
15
1
5


#### Aggregations

In [55]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

print(np.sum(matrix, axis=0))   # (sum of columns)
print(np.sum(matrix, axis=1))   # (sum of rows)

[[1 2]
 [3 4]]
[4 6]
[3 7]


## 7. Broadcasting

In [ ]:
# Numpy can perform operations on arrays of different shapes:

In [58]:
arr = np.array([1, 2, 3])
result = arr + 5   # Adds 5 to each element
print(result)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
result = matrix + arr   # Adds arr to each row of matrix
print(result)

[6 7 8]
[[2 4 6]
 [5 7 9]]


## 8. Linear Algebra

In [60]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

[[1 2]
 [3 4]]


#### Eigen-values and eigen-vectors

In [61]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)

#### Matrix inverse

In [62]:
inv_matrix = np.linalg.inv(matrix)

#### Dereminant

In [63]:
det = np.linalg.det(matrix)

#### Solve linear equation
#### For equation: 1*x0 + 2*x1 = 5 and 3*x0 + 4*x1 = 6

In [64]:
solution = np.linalg.solve(matrix, [5, 6])

## 9. Random Sampling

In [65]:
arr = np.array([1, 2, 3, 4, 5])

#### Random choice

In [66]:
random_sample = np.random.choice(arr, size=3, replace=False)
print(random_sample)

[2 3 5]


#### Random shuffle

In [71]:
print(np.random.shuffle(arr))

None


#### Random permutations

In [72]:
permuted = np.random.permutation(arr)
print(permuted)

[4 2 5 1 3]


## 10. Handling Missing Data

In [74]:
arr = np.array([1, 2, np.nan, 4, 5])
arr

array([ 1.,  2., nan,  4.,  5.])

#### Check for NaN Values

In [76]:
has_nan = np.isnan(arr).any()   # True
print(has_nan)

True


#### Remove NaN values

In [77]:
clean_arr = arr[~np.isnan(arr)]
print(clean_arr)

[1. 2. 4. 5.]


#### Replace NaN with 0

In [82]:
arr[np.isnan(arr)]=0
print(arr)

[1. 2. 0. 4. 5.]


## 11. Saving and Loding Arrays

#### Save single array

In [83]:
np.save('my_array.npy', arr)

#### Load array

In [84]:
loaded_arr = np.load('my_array.npy')

#### Save multiple arrays

In [85]:
np.savez('arrays.npz', arr1=arr1, arr2=arr2)

NameError: name 'arr1' is not defined

#### Load multiple arrays

In [86]:
loaded = np.load('arrays.npz')
arr1 = loaded['arr1']
arr2 = loaded['arr2']

FileNotFoundError: [Errno 2] No such file or directory: 'arrays.npz'

## 12. Memory Usage

#### Total bytes consumed by elements

In [87]:
size_in_bytes = arr.nbytes
print(size_in_bytes)

40


#### Size of one element in bytes

In [88]:
itemsize = arr.itemsize
print(itemsize)

8


## 13. Vectorized Operations

In [89]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

#### Vectorized operation are much faster and Python loops

In [90]:
result = np.sin(arr) + np.cos(arr) ** 2
print(result)

[ 1.13339757  1.08247562  1.12120515 -0.32955251 -0.87846004]


## Best Practices

1. *Avoid loops*: Use vectorized operations whenever possible
2. *Preallocate arrays*: Use np.zeros() or np.empty() when you know the final size
3. *Use views instead of copies*: Slicing creates views by default
4. *Be explicit with copies*: Use .copy() when you need a new array
5. *Use broadcasting*: It's more efficient than expanding arrays manually